### ISSUE TITLE
Carn Evil/midway bootrom

### ISSUE THREAD

**Issue by pnill** [xclusivor/CarnEvil-Research#1]
Would open a PR but I'll let you decide how to reference it, I've been a little obsessed lately with trying to take a hybrid approach to a few midway games when it comes to emulation (dynarec, pre-extracted CHD/cached content read from disk when the instructions are referenced etc.).

Anyway with that stumbled on your repo, and the documentation of the bootloader so wanted to show you this that I also stumbled upon:
https://github.com/historicalsource/midwayvideo/blob/main/biosrom/bios/cmain.c

Will also have to check out your python adaptations of the original exes from xentax as it looks like xentax is gone.

**Comment by xclusivor** [comment]
Ooh, this is interesting I’ll take a closer look! This repo is very outdated and inaccurate. I’ve discovered a lot more and have an annotated disassembly/decomp of most of the game. I haven’t taken a good look at the bootloader tho mostly poked around to figure out how the interrupts were working. There’s also a lot of debug prints I was trying to screen. I’ll get this updated in the next couple of days. And if you have binary ninja you’re welcome to my annotated database.

**Comment by pnill** [comment]
I mostly use IDA, not really a binja fan. Cool that you've reversed a lot of it, it turns out that the blitz and 3dfx/goose sound code in those libs are still utilized in the Carnevil code so you'd be able to document/identify a lot of the statically linked library functions pretty easily if you utilize string references or signatures on another debug version of something.

My plan going forward if I ever sit down and look at mame is to try to use signature detection to find blocks of code containing the library functions and implement native versions instead when they're attempted to be called within the state machine, extract the CHD and reference on disk raw assets instead and remove the sound chip/play samples directly in an effort to improve performance on weaker hardware.

Still, will be interesting to see what else you've discovered was never a fan of Carnevil myself haven't really ever played it I've just been consistently annoyed with the performance mame offers in numerous titles including this.

**Comment by pnill** [comment]
Oh also if you use discord... I have the same alias there.
